/* Loading */

export const LOADINGGENRES_REQUEST = 'LOADINGGENRES_REQUEST'
export const LOADINGGENRES_SUCCESS = 'LOADINGGENRES_SUCCESS'
export const LOADINGGENRES_FAILURE = 'LOADINGGENRES_FAILURE'

/* Seting genre.names */

export const SET_GENRENAME = 'SET_GENRENAME'