/* Loading */

export const LOADINGGENRES_REQUEST = 'LOADINGGENRES_REQUEST'
export const LOADINGGENRES_SUCCESS = 'LOADINGGENRES_SUCCESS'
export const LOADINGGENRES_FAILURE = 'LOADINGGENRES_FAILURE'

/* Loading Songlist */

export const LOADINGSONGLIST_REQUEST = 'LOADINGSONGLIST_REQUEST'
export const LOADINGSONGLIST_SUCCESS = 'LOADINGSONGLIST_SUCCESS'

export const LOADINGSONGINFO_REQUEST = 'LOADINGSONGINFO_REQUEST'
export const LOADINGSONGINFO_SUCCESS = 'LOADINGSONGINFO_SUCCESS'

/* Setting genre.names */

export const SET_GENRENAME = 'SET_GENRENAME'

/* Setting songlist.names */

export const SET_SONGLISTNAME = 'SET_SONGLISTNAME'

